<?php

namespace WPML\LanguageEditor\Presets;

class CountriesData {

	public static function data() {

return [
			[ 'code' => 'AF', 'english_name' => 'Afghanistan' ],
			[ 'code' => 'AL', 'english_name' => 'Albania' ],
			[ 'code' => 'AM', 'english_name' => 'Armenia' ],
			[ 'code' => 'AO', 'english_name' => 'Angola' ],
			[ 'code' => 'AR', 'english_name' => 'Argentina' ],
			[ 'code' => 'AT', 'english_name' => 'Austria' ],
			[ 'code' => 'AU', 'english_name' => 'Australia' ],
			[ 'code' => 'AZ', 'english_name' => 'Azerbaijan' ],
			[ 'code' => 'BA', 'english_name' => 'Bosnia & Herzegovina' ],
			[ 'code' => 'BD', 'english_name' => 'Bangladesh' ],
			[ 'code' => 'BE', 'english_name' => 'Belgium' ],
			[ 'code' => 'BG', 'english_name' => 'Bulgaria' ],
			[ 'code' => 'BO', 'english_name' => 'Bolivia' ],
			[ 'code' => 'BR', 'english_name' => 'Brazil' ],
			[ 'code' => 'BY', 'english_name' => 'Belarus' ],
			[ 'code' => 'CA', 'english_name' => 'Canada' ],
			[ 'code' => 'CH', 'english_name' => 'Switzerland' ],
			[ 'code' => 'CL', 'english_name' => 'Chile' ],
			[ 'code' => 'CN', 'english_name' => 'China' ],
			[ 'code' => 'CO', 'english_name' => 'Colombia' ],
			[ 'code' => 'CR', 'english_name' => 'Costa Rica' ],
			[ 'code' => 'CU', 'english_name' => 'Cuba' ],
			[ 'code' => 'CZ', 'english_name' => 'Czechia' ],
			[ 'code' => 'DE', 'english_name' => 'Germany' ],
			[ 'code' => 'DK', 'english_name' => 'Denmark' ],
			[ 'code' => 'DO', 'english_name' => 'Dominican Republic' ],
			[ 'code' => 'EC', 'english_name' => 'Ecuador' ],
			[ 'code' => 'EE', 'english_name' => 'Estonia' ],
			[ 'code' => 'ER', 'english_name' => 'Eritrea' ],
			[ 'code' => 'ES', 'english_name' => 'Spain' ],
			[ 'code' => 'ET', 'english_name' => 'Ethiopia' ],
			[ 'code' => 'FI', 'english_name' => 'Finland' ],
			[ 'code' => 'FR', 'english_name' => 'France' ],
			[ 'code' => 'GB', 'english_name' => 'United Kingdom' ],
			[ 'code' => 'GE', 'english_name' => 'Georgia' ],
			[ 'code' => 'GQ', 'english_name' => 'Equatorial Guinea' ],
			[ 'code' => 'GR', 'english_name' => 'Greece' ],
			[ 'code' => 'GT', 'english_name' => 'Guatemala' ],
			[ 'code' => 'HK', 'english_name' => 'Hong Kong SAR China' ],
			[ 'code' => 'HN', 'english_name' => 'Honduras' ],
			[ 'code' => 'HR', 'english_name' => 'Croatia' ],
			[ 'code' => 'HT', 'english_name' => 'Haiti' ],
			[ 'code' => 'HU', 'english_name' => 'Hungary' ],
			[ 'code' => 'ID', 'english_name' => 'Indonesia' ],
			[ 'code' => 'IE', 'english_name' => 'Ireland' ],
			[ 'code' => 'IL', 'english_name' => 'Israel' ],
			[ 'code' => 'IN', 'english_name' => 'India' ],
			[ 'code' => 'IR', 'english_name' => 'Iran' ],
			[ 'code' => 'IS', 'english_name' => 'Iceland' ],
			[ 'code' => 'IT', 'english_name' => 'Italy' ],
			[ 'code' => 'JP', 'english_name' => 'Japan' ],
			[ 'code' => 'KH', 'english_name' => 'Cambodia' ],
			[ 'code' => 'KR', 'english_name' => 'South Korea' ],
			[ 'code' => 'KZ', 'english_name' => 'Kazakhstan' ],
			[ 'code' => 'LI', 'english_name' => 'Liechtenstein' ],
			[ 'code' => 'LK', 'english_name' => 'Sri Lanka' ],
			[ 'code' => 'LT', 'english_name' => 'Lithuania' ],
			[ 'code' => 'LU', 'english_name' => 'Luxembourg' ],
			[ 'code' => 'LV', 'english_name' => 'Latvia' ],
			[ 'code' => 'MK', 'english_name' => 'North Macedonia' ],
			[ 'code' => 'MN', 'english_name' => 'Mongolia' ],
			[ 'code' => 'MO', 'english_name' => 'Macao SAR China' ],
			[ 'code' => 'MT', 'english_name' => 'Malta' ],
			[ 'code' => 'MX', 'english_name' => 'Mexico' ],
			[ 'code' => 'MY', 'english_name' => 'Malaysia' ],
			[ 'code' => 'MZ', 'english_name' => 'Mozambique' ],
			[ 'code' => 'NI', 'english_name' => 'Nicaragua' ],
			[ 'code' => 'NL', 'english_name' => 'Netherlands' ],
			[ 'code' => 'NO', 'english_name' => 'Norway' ],
			[ 'code' => 'NP', 'english_name' => 'Nepal' ],
			[ 'code' => 'NZ', 'english_name' => 'New Zealand' ],
			[ 'code' => 'PA', 'english_name' => 'Panama' ],
			[ 'code' => 'PE', 'english_name' => 'Peru' ],
			[ 'code' => 'PH', 'english_name' => 'Philippines' ],
			[ 'code' => 'PK', 'english_name' => 'Pakistan' ],
			[ 'code' => 'PL', 'english_name' => 'Poland' ],
			[ 'code' => 'PR', 'english_name' => 'Puerto Rico' ],
			[ 'code' => 'PT', 'english_name' => 'Portugal' ],
			[ 'code' => 'PY', 'english_name' => 'Paraguay' ],
			[ 'code' => 'RO', 'english_name' => 'Romania' ],
			[ 'code' => 'RS', 'english_name' => 'Serbia' ],
			[ 'code' => 'RU', 'english_name' => 'Russia' ],
			[ 'code' => 'SE', 'english_name' => 'Sweden' ],
			[ 'code' => 'SG', 'english_name' => 'Singapore' ],
			[ 'code' => 'SI', 'english_name' => 'Slovenia' ],
			[ 'code' => 'SK', 'english_name' => 'Slovakia' ],
			[ 'code' => 'SO', 'english_name' => 'Somalia' ],
			[ 'code' => 'SV', 'english_name' => 'El Salvador' ],
			[ 'code' => 'TH', 'english_name' => 'Thailand' ],
			[ 'code' => 'TR', 'english_name' => 'Turkey' ],
			[ 'code' => 'TW', 'english_name' => 'Taiwan' ],
			[ 'code' => 'UA', 'english_name' => 'Ukraine' ],
			[ 'code' => 'US', 'english_name' => 'United States' ],
			[ 'code' => 'UY', 'english_name' => 'Uruguay' ],
			[ 'code' => 'UZ', 'english_name' => 'Uzbekistan' ],
			[ 'code' => 'VE', 'english_name' => 'Venezuela' ],
			[ 'code' => 'VN', 'english_name' => 'Vietnam' ],
			[ 'code' => 'ZA', 'english_name' => 'South Africa' ],
		];
	}
}
