<?php

namespace WPML\LanguageEditor\Presets;

class LanguagePresetsDefaultPairs {

	public static function data() {

return [
	[ 'en', 'US' ],
	[ 'es', 'ES' ],
	[ 'de', 'DE' ],
	[ 'fr', 'FR' ],
	[ 'ar', null ],
	[ 'bs-latn', 'BA' ],
	[ 'bg', 'BG' ],
	[ 'ca', null ],
	[ 'cs', 'CZ' ],
	[ 'sk', 'SK' ],
	[ 'cy', null ],
	[ 'da', 'DK' ],
	[ 'el', 'GR' ],
	[ 'eo', null ],
	[ 'et', 'EE' ],
	[ 'eu', null ],
	[ 'fa', 'IR' ],
	[ 'fi', 'FI' ],
	[ 'ga', 'IE' ],
	[ 'he', 'IL' ],
	[ 'hi', 'IN' ],
	[ 'hr', 'HR' ],
	[ 'hu', 'HU' ],
	[ 'hy', 'AM' ],
	[ 'id', 'ID' ],
	[ 'is', 'IS' ],
	[ 'it', 'IT' ],
	[ 'ja', 'JP' ],
	[ 'ko', 'KR' ],
	[ 'ku-arab', null ],
	[ 'lv', 'LV' ],
	[ 'lt', 'LT' ],
	[ 'mk', 'MK' ],
	[ 'mt', 'MT' ],
	[ 'mn-cyrl', 'MN' ],
	[ 'ne', 'NP' ],
	[ 'nl', 'NL' ],
	[ 'no', 'NO' ],
	[ 'pa-guru', null ],
	[ 'pl', 'PL' ],
	[ 'pt', 'PT' ],
	[ 'pt', 'BR' ],
	[ 'ro', 'RO' ],
	[ 'ru', 'RU' ],
	[ 'sl', 'SI' ],
	[ 'so', 'SO' ],
	[ 'sq', 'AL' ],
	[ 'sr-cyrl', 'RS' ],
	[ 'sr-latn', 'RS' ],
	[ 'sv', 'SE' ],
	[ 'ta', 'IN' ],
	[ 'th', 'TH' ],
	[ 'tr', 'TR' ],
	[ 'uk', 'UA' ],
	[ 'ur', 'PK' ],
	[ 'uz-latn', 'UZ' ],
	[ 'vi', 'VN' ],
	[ 'yi', null ],
	[ 'zh-hans', 'CN' ],
	[ 'zu', null ],
	[ 'zh-hant', 'TW' ],
	[ 'ms-latn', 'MY' ],
	[ 'gl', null ],
	[ 'bn', 'BD' ],
	[ 'az-latn', 'AZ' ],
	[ 'sw', null ],
	[ 'fr', 'CA' ],
];
	}
}
