<?php

abstract class WPML_TM_Email_View {

	const FOOTER_TEMPLATE = 'email-footer.twig';
	const HEADER_TEMPLATE = 'email-header.twig';

	protected $template_service;

	public function __construct( WPML_Twig_Template $template_service ) {
		$this->template_service = $template_service;
	}

	public function render_header( $username = '' ) {
		$model = array(
			/* translators: Formal greeting at the top of an email WPML sends. %s: the name of the person the email goes to. */
			'greetings' => sprintf( __( 'Dear %s,', 'sitepress' ), $username ),
		);

		return $this->template_service->show( $model, self::HEADER_TEMPLATE );
	}

	public function render_casual_header( $first_name = '' ) {
		$model = array(
			/* translators: Friendly greeting at the top of an email WPML sends. %s: the first name of the person the email goes to. */
			'greetings' => sprintf( __( 'Hi %s,', 'sitepress' ), $first_name ),
		);

		return $this->template_service->show( $model, self::HEADER_TEMPLATE );
	}

	protected function render_email_footer( $bottom_text = '' ) {
		$site_url = get_bloginfo( 'url' );

		$model = array(
			'bottom_text' => $bottom_text,
			'wpml_footer' => sprintf(
				/* translators: %s: link to the site. */
				esc_html__( 'Generated by WPML plugin, running on %s.', 'sitepress' ),
				'<a href="' . $site_url . '" style="color: #ffffff;">' . $site_url . '</a>'
			),
		);

		return $this->template_service->show( $model, self::FOOTER_TEMPLATE );
	}
}
